[package]
name = "moonrust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.91"
nom = "7"
clap = { version = "4.1", features = ["cargo", "derive"] }
rand = "0.8.4"
getrandom = { version = "0.2", features = ["js"] }
